feat: Remove unecessary chroot and fix bugs

diff --git a/setup/includes/configs b/setup/includes/configs
--- a/setup/includes/configs
+++ b/setup/includes/configs
@@ -11,14 +11,30 @@ function copy_bin() {
 export -f copy_bin
 
 
-# After the chroot
-function copy_network_manager_configs(){
-  if ! sudo cp -rfvT "$SCRIPT_DIR"/files/system/etc/NetworkManager/ /mnt/etc/NetworkManager/; then
-    echo "Failed to copy NetworkManager configs to /etc/NetworkManager/conf.d/" >&2
+function copy_wayfire_ini(){
+  local user_home=$1
+  mkdir -p "$user_home"/.config
+  cp -v "$SCRIPT_DIR"/../config/wayfire.ini "$user_home"/.config/wayfire.ini
+}
+export -f copy_wayfire_ini
+
+function copy_wpa_supplicant_conf(){
+  local src=/etc/wpa_supplicant/wpa_supplicant.conf
+  local dst=/mnt/etc/wpa_supplicant/wpa_supplicant.conf
+  if [[ ! -f "$src" ]]; then
+    echo "no wpa config in $src" >&2
     return 1
   fi
+
+  # Create target directory if it doesn't exist
+  mkdir -p /mnt/etc/wpa_supplicant/
+
+  if ! cp -v "$src" "$dst"; then
+    echo "Failed to copy wpa_supplicant.conf" >&2
+    return 2
+  fi
 }
-export -f copy_network_manager_configs
+export -f copy_wpa_supplicant_conf
 
 # Copy cappuccino rofi theme
 function copy_rofi_usr_theme(){
@@ -29,15 +45,6 @@ function copy_rofi_usr_theme(){
   fi
 }
 export -f copy_rofi_usr_theme
-
-# After the chroot
-function copy_modprobe(){
-  if ! sudo cp -rfvT "$SCRIPT_DIR"/files/system/etc/modprobe/ /mnt/etc/modprobe.d/; then
-    echo "Failed to copy modprobe configs to /etc/modprobe.d/" >&2
-    return 1
-  fi
-}
-export -f copy_modprobe
 
 function copy_dots(){
   if ! sudo cp -rfvT "$SCRIPT_DIR"/files/system/.config/ "$HOME"/.config/; then
@@ -56,11 +63,3 @@ function copy_dots(){
   fi
 }
 export -f copy_dots
-
-function copy_iwd(){
-  if ! sudo cp -rfvT /var/lib/iwd/ /mnt/var/lib/iwd; then
-    echo "Failed to copy iwd configs to /mnt/var/lib/" >&2
-    return 1
-  fi
-}
-export -f copy_iwd
diff --git a/setup/includes/package_installer b/setup/includes/package_installer
--- a/setup/includes/package_installer
+++ b/setup/includes/package_installer
@@ -13,10 +13,10 @@ function export_package_group(){
 export -f export_package_group
 
 function install_xbps_packages() {
-  local group_name
-  local package_list=("$@")
-  if ! xbps-install -y "${package_list[@]}"; then
-    echo "Failed to install packages from group $group_name" >&2
+  local -n package_list=$1
+  local root=$2
+  if ! xbps-install -y -r "$root" "${package_list[@]}"; then
+    echo "Failed to install packages" >&2
     return 1
   fi
 }
diff --git a/setup/includes/stage b/setup/includes/stage
--- a/setup/includes/stage
+++ b/setup/includes/stage
@@ -9,8 +9,8 @@ source "$SCRIPT_DIR/includes/network"
 # shellcheck source=utils
 source "$SCRIPT_DIR/includes/utils"
 
-# shellcheck source=copy
-source "$SCRIPT_DIR/includes/copy"
+# shellcheck source=configs
+source "$SCRIPT_DIR/includes/configs"
 
 # shellcheck source=package_installer
 source "$SCRIPT_DIR/includes/package_installer"
@@ -81,9 +81,8 @@ stage_zero(){
   read -p 'Set your hostname: ' hostname
   read -p 'Set your username: ' username
   read -sp 'Set your root password: ' password
-  echo ""
+  echo " " >&2
 
-  export hostname
   export password
   export username
 
@@ -93,7 +92,6 @@ stage_zero(){
   boot_mode=$(get_boot_mode)
   stage0_packages_str="$(export_package_group "stage0" "xbps")"
 
-  export stage0_packages_str
   export boot_mode
   # Install chrony and start the service
   # Setup a time zone
@@ -116,26 +114,32 @@ stage_zero(){
   # install wayfire
   # Instal alacritty
   # Install nerd-fonts
+  # Copy the wayfire inis
+  # Set XDG_RUNTIME_DIR into the profile --- make a util function for this as this is common
 
+  copy_wpa_supplicant_conf
 
   x_chroot /mnt /bin/bash -c "
-    xbps-install -Suy xbps
-    xbps-install -uy
-    xbps-install -y base-system
-    xbps-remove -y base-container-full
-    xbps-install -y fontconfig
-    fc-cache -fv
-
-    echo \"\$hostname\" > /etc/hostname
-    echo \"root:\$password\" | chpasswd -c SHA512
-
-    echo 'Setting up new user...'
-    useradd -m \"\$username\"
-    echo \"\$username:\$password\" | chpasswd -c SHA512
-    usermod -aG wheel \"\$username\"
-    usermod -aG audio \"\$username\"
-    usermod -aG video \"\$username\"
-    sed -i '/^#\s*%wheel ALL=(ALL:ALL) NOPASSWD: ALL/s/^# //' /etc/sudoers
+    if ! xbps-install -Suy xbps; then
+        echo 'Failed to update xbps' >&2
+        exit 1
+    fi
+    if ! xbps-install -uy; then
+        echo 'Failed to update system' >&2
+        exit 1
+    fi
+    if ! xbps-install -y base-system; then
+        echo 'Failed to install base system' >&2
+        exit 1
+    fi
+    if ! xbps-remove -y base-container-full; then
+        echo 'Failed to remove base-container-full' >&2
+        exit 1
+    fi
+    if ! xbps-install -y fontconfig; then
+        echo 'Failed to install fontconfig' >&2
+        exit 1
+    fi
 
     echo 'Preparing grub...'
     if ! install_grub \"\$boot_mode\"; then
@@ -147,63 +151,74 @@ stage_zero(){
         echo 'xbps-reconfigure failed' >&2
         exit 1
     fi
-
-    echo 'Installing packages...'>&2
-    if [[ -n \"\${stage0_packages_str}\" ]]; then
-      readarray -t stage0_packages <<< \"\${stage0_packages_str}\"
-      count=0
-      echo 'Installing basic packages' >&2
-      while ((count < 5)); do
-        if ! install_xbps_packages \"\${stage0_packages[@]}\"; then
-            echo 'Failed to install xbps packages...retrying' >&2
-            ((count++))
-            continue
-        fi
-        echo 'Successfully installed packages' >&2
-        break
-      done
-    fi
-
-    if ((count == 5)); then
-      echo 'Failed to install packages. Check internet connection and try again.' >&2
-      exit 1
-    fi
-
-    echo 'Performing services setup...'>&2
-    sleep 1
-    service -c /etc/runit/runsvdir/default/ dbus || true
-    service -c /etc/runit/runsvdir/default/ dhcpcd || true
-    service -c /etc/runit/runsvdir/default/ chronyd || true
-    service -c /etc/runit/runsvdir/default/ tlp || true
-    service -c /etc/runit/runsvdir/default/ rtkit || true
-    service -c /etc/runit/runsvdir/default/ seatd || true
-    service -c /etc/runit/runsvdir/default/ wpa_supplicant || true
-    service -c /etc/runit/runsvdir/default/ xdg-run-generator || true
-
-    if ! mkdir -p /etc/pipewire/pipewire.conf.d; then
-      echo \"Failed to create pipewire folder\"
-    fi
-
-    if ! ln -s /usr/share/examples/pipewire/20-pipewire-pulse.conf /etc/pipewire/pipewire.conf.d/; then
-      echo \"Pipewire configuration failed to link\"
-    fi
-
-    mkdir -p /etc/alsa/conf.d
-    ln -s /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d
-    ln -s /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d
-
-    echo 'Preparing for stage 1...'
-    mkdir -p /var/install/
-    touch /var/install/stage1
   "
 
-  echo 'Stage 0 complete, rebooting into the system to run stage 1...'
+  echo 'Installing packages...'>&2
+  if [[ -n "${stage0_packages_str}" ]]; then
+    local stage0_packages
+    local count=0
+    readarray -t stage0_packages <<< "${stage0_packages_str}"
+    echo 'Installing basic packages' >&2
+    while ((count < 5)); do
+    if ! install_xbps_packages stage0_packages /mnt; then
+          echo 'Failed to install xbps packages...retrying' >&2
+          ((count++))
+          continue
+      fi
+      echo 'Successfully installed packages' >&2
+      break
+    done
+  fi
+
+  if ((count == 5)); then
+    echo 'Failed to install packages. Check internet connection and try again.' >&2
+    exit 1
+  fi
+
+  if ! mkdir -p /mnt/etc/pipewire/pipewire.conf.d; then
+    echo "Failed to create pipewire folder" >&2
+  fi
+
+  if ! ln -s /mnt/usr/share/examples/pipewire/20-pipewire-pulse.conf /mnt/etc/pipewire/pipewire.conf.d/; then
+    echo "Pipewire configuration failed to link"
+  fi
+
+  mkdir -p /mnt/etc/alsa/conf.d
+  ln -s /mnt/usr/share/alsa/alsa.conf.d/50-pipewire.conf /mnt/etc/alsa/conf.d
+  ln -s /mnt/usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /mnt/etc/alsa/conf.d
+
+  echo "Setting up hostname" >&2
+  echo "$hostname" > /mnt/etc/hostname
+
+  x_chroot /mnt /bin/bash -c "
+    echo \"root:\$password\" | chpasswd -c SHA512
+
+    echo 'Setting up new user...' >&2
+    useradd -m \"\$username\"
+    echo \"\$username:\$password\" | chpasswd -c SHA512
+    usermod -aG wheel \"\$username\"
+    usermod -aG audio \"\$username\"
+    usermod -aG video \"\$username\"
+    usermod -aG _seatd \"\$username\"
+    sed -i '/^#\s*%wheel ALL=(ALL:ALL) NOPASSWD: ALL/s/^# //' /etc/sudoers
+
+    echo 'Performing services setup...'>&2
+    for svc in dbus dhcpcd chronyd tlp rtkit seatd xdg-run-generator; do
+        if ! service -c /etc/runit/runsvdir/default/ \$svc; then
+            echo \"Warning: Failed to enable \$svc\" >&2
+        fi
+    done
+  "
+
+  map_string  "export XDG_RUNTIME_DIR=" "export XDG_RUNTIME_DIR=/run/user/\$(id -u)" /mnt/etc/profile.d/bash.sh
+  copy_wayfire_ini "/mnt/home/$username"
+
+  echo 'Install complete. Rebooting into the system'
   sleep 5
-  shutdown -r now
+  # shutdown -r now
 }
 
 stage_one(){
-
   if ! is_internet_connected; then
     if ! handle_internet_connection; then
       echo "Internet is not connected. Please connect to the internet and run this script again with --stage 1."
@@ -217,7 +232,7 @@ stage_one(){
   readarray -t stage1_packages <<< "$(export_package_group "stage1" "pacman")"
 
   if ! install_xbps_packages "${stage1_packages[@]}"; then
-    echo "Failed to install pacman packages"
+    echo "Failed to install xbps packages"
     exit 1
   fi
 
diff --git a/setup/includes/utils b/setup/includes/utils
--- a/setup/includes/utils
+++ b/setup/includes/utils
@@ -1,4 +1,34 @@
 #!/bin/bash
+
+function map_string() {
+  # Check parameters
+  if [ "$#" -ne 3 ]; then
+    echo "Usage: map_string key replacement file" >&2
+    return 1
+  fi
+
+  local key=$1
+  local replacement=$2
+  local file=$3
+  if [ ! -f "$file" ]; then
+    echo "Error: File '$file' not found" >&2
+    return 1
+  fi
+
+  local key_escaped
+  local replacement_escaped
+  key_escaped=$(printf '%s\n' "$key" | sed 's/[[\.*^$/]/\\&/g')
+  replacement_escaped=$(printf '%s\n' "$replacement" | sed 's/[[\.*^$/]/\\&/g')
+
+  if ! grep -Fs "$key" "$file"; then
+      echo "$replacement" >> "$file"
+      return 0
+  fi
+
+  sed -i "s/$key_escaped/$replacement_escaped/g" "$file"
+}
+export -f map_string
+
 function select_from_list() {
   local -n list=$1  # Creates reference to original array
   local max_items=$2
@@ -173,13 +203,13 @@ function x_chroot() {
   printf "\033[1m=> Entering chroot $CHROOT\033[m\n"
   export PS1="[xchroot $CHROOT] $PS1"
   chroot "$CHROOT" "${@:-$INNER_SHELL}"
-  STATUS=$?
+  local STATUS=$?
   if [ $STATUS -ne 0 ]; then
     printf "\033[1m=> Exited chroot $CHROOT\033[m\n"
   else
     printf "\033[1m=> Exited chroot $CHROOT with status $STATUS\033[m\n"
   fi
-  exit $STATUS
+  return $STATUS
 }
 
 export -f x_chroot
