fix: grub error

diff --git a/setup/includes/network b/setup/includes/network
--- a/setup/includes/network
+++ b/setup/includes/network
@@ -51,35 +51,42 @@ function select_wireless_network() {
         echo "No interface provided."
         return 1
     fi
-
+    # Prompt the user to select a wireless network
+    local selection='0'
     local interface=$1
     local networks
-    mapfile -t networks < <(iw dev "$interface" scan | grep -E 'SSID: .+?$' | sed 's/^.*SSID: //')
 
-    if [ ${#networks[@]} -eq 0 ]; then
-        echo "No wireless networks found." >&2
-        return 1
-    fi
+    while [[ $selection == '0' ]]; do
 
-    echo "Available wireless networks:" >&2
-    local i=0
-    for ssid in "${networks[@]}"; do
-        echo "[$i] $ssid" >&2
-        ((i++))
+      mapfile -t networks < <(echo "rescan"; echo "exit"; iw dev "$interface" scan | grep -E 'SSID: .+?$' | sed 's/^.*SSID: //')
+
+      echo "Available wireless networks:" >&2
+      local i=0
+      for ssid in "${networks[@]}"; do
+          echo "[$i] $ssid" >&2
+          ((i++))
+      done
+
+
+      read -rp "Select the wireless network to use [0-$((i-1))]: " selection
+
+      # Validate the input
+      if ! [[ "$selection" =~ ^[0-9]+$ ]] || [ "$selection" -ge "$i" ]; then
+          echo "Invalid selection." >&2
+          return 1
+      fi
+      if [[ $selection == '1' ]]; then
+        return 1;
+      fi
+
+      # Return the selected wireless network SSID
+      if (( selection > 2 )); then
+        echo "${networks[$selection]}"
+        return 0
+      fi
+
     done
 
-    # Prompt the user to select a wireless network
-    local selection
-    read -rp "Select the wireless network to use [0-$((i-1))]: " selection
-
-    # Validate the input
-    if ! [[ "$selection" =~ ^[0-9]+$ ]] || [ "$selection" -ge "$i" ]; then
-        echo "Invalid selection." >&2
-        return 1
-    fi
-
-    # Return the selected wireless network SSID
-    echo "${networks[$selection]}"
 }
 export -f select_wireless_network
 
diff --git a/setup/includes/stage b/setup/includes/stage
--- a/setup/includes/stage
+++ b/setup/includes/stage
@@ -70,12 +70,19 @@ stage_zero(){
   read -p 'Set your hostname: ' hostname
   read -p 'Set your username: ' username
   read -sp 'Set your root password: ' password
+  echo ""
 
   local stage0_packages_str
   local stage0_packages
+  local boot_mode
+  boot_mode=$(get_boot_mode)
   stage0_packages_str="$(export_package_group "stage0" "xbps")"
 
-xchroot /mnt /bin/bash << EOF
+chroot /mnt /usr/bin/env hostname="$hostname" username="$username" password="$password" /bin/bash << 'EOF'
+    # Source the files
+    source /opt/install/includes/bootloader
+    source /opt/install/includes/package_installer
+
     # Update xbps
     xbps-install -Suy xbps
     xbps-install -uy
@@ -101,21 +108,17 @@ xchroot /mnt /bin/bash << EOF
     useradd -m $username
     echo "$username:$password" | chpasswd
     usermod -aG wheel "$username"
-    usermod -aG lp "$username"
-    usermod -aG dbus "$username"
-    usermod -aG input "$username"
+    usermod -aG audio "$username"
     sed -i '/^#\s*%wheel ALL=(ALL:ALL) NOPASSWD: ALL/s/^# //' /etc/sudoers
 
     echo 'Preparing grub...'
-    sleep 5
-    if ! install_grub; then
-        echo 'Grub installation failed'
+    if ! install_grub "$boot_mode"; then
+        echo 'Grub installation failed' >&2
         exit 1
     fi
-    sleep 5
 
     if ! xbps-reconfigure -fa; then
-        echo 'xbps-reconfigure failed'
+        echo 'xbps-reconfigure failed' >&2
         exit 1
     fi
 
