feat: Finalize stage0 setup

diff --git a/setup/includes/service b/setup/includes/service
--- a/setup/includes/service
+++ b/setup/includes/service
@@ -1,68 +1,97 @@
 #!/bin/bash
+# TODO Support for Void Linux first boot services
+# you can achieve this by creating the service symlinks in `/etc/runit/runsvdir/default/`. This is the directory that gets copied to `/run/runit/runsvdir/current` on first boot.
 
 function service(){
     # Check if we have enough arguments
-    if [[ $# -lt 2 ]]; then
+    local operation="$1"
+    shift
+    if [[ $# -lt 2 && $operation != "-l" && $operation != "--list" ]]; then
         cat << 'EOF'
 Usage: service <|-c|--create |-r|--remove> <service_name>
 
 Options:
-  -c|--create <service_name>  Create a new service
-  -r|--remove <service_name>  Remove a service
-  -l|--list                   List all services
+  -c|--create <target_dir> <service_name> [up] Create a new service
+  -r|--remove <target_dir> <service_name> Remove a service
+  -l|--list <target_dir>                  List all services
 EOF
       return 1
     fi
 
-  case "$1" in
+  local target_dir="$1"
+  local service_name="$2"
+  local start="$3"
+
+   if [[ -z "$1" ]]; then
+       echo "Error: target directory required for list operation" >&2
+      return 1
+   fi
+
+  if [[ ! -d "$target_dir" ]]; then
+    echo "Error: '$target_dir' is not a directory" >&2
+    return 1
+  fi
+
+  case "$operation" in
     -c|--create)
-      if [[ ! -d "/etc/sv/$2" ]]; then
-          echo "Service '$2' doesn't exist in /etc/sv/" >&2
+      if [[ ! -d "/etc/sv/$service_name" ]]; then
+          echo "Service '$service_name' doesn't exist in /etc/sv/" >&2
+          return 1
+      fi
+      if [[ -e "$target_dir$service_name" ]]; then
+          echo "Service '$service_name' is already enabled" >&2
           return 1
       fi
 
-      if [[ -e "/var/service/$2" ]]; then
-          echo "Service '$2' is already enabled" >&2
-          return 1
-      fi
-
-      if ! ln -s "/etc/sv/$2" /var/service/; then
+      echo "Creating ln $target_dir$service_name">&2
+      if ! ln -s "/etc/sv/$service_name" "$target_dir"; then
         return 1
+      fi
+      if [[ -z "$start" ]]; then
+        return 0
       fi
 
       # Wait a moment for runit to detect the new service
-      echo "Starting service... '$2'" >&2
+      echo "Starting service... '$service_name'" >&2
       sleep 1
 
-      if ! sv up "$2"; then
+      if ! sv up "$service_name"; then
         echo "Failed to start service." >&2
         return 1
       fi
     ;;
     -r|--remove)
-      if [[ ! -e "/var/service/$2" ]]; then
-          echo "Service '$2' is not enabled" >&2
+      if [[ ! -e "$target_dir$service_name" ]]; then
+          echo "Service '$service_name' is not enabled" >&2
           return 1
       fi
 
-      if ! sv down "$2"; then
+      if ! sv down "$service_name"; then
         echo "Service failed to stop. Either not running or doesn't exist." >&2
         return 1
       fi
-      echo "Stopping service... '$2'" >&2
+      echo "Stopping service... '$service_name'" >&2
       sleep 1
 
-      if ! rm "/var/service/$2"; then
+      if ! rm "$target_dir$service_name"; then
         echo "Failed to remove service." >&2
         return 1
       fi
     ;;
     -l|--list)
-       find /var/service/ -mindepth 1 -printf "%f\n"
-      ;;
-    *)
-        echo "Usage: service <|-c|--create |-r|--remove> <service_name>" >&2
+     find "$target_dir" -mindepth 1 -printf "%f\n"
     ;;
+    *)
+    cat << 'EOF'
+Usage: service <|-c|--create |-r|--remove> <service_name>
+
+Options:
+  -c|--create <target_dir> <service_name> <up> Create a new service
+  -r|--remove <target_dir> <service_name> Remove a service
+  -l|--list <target_dir>                  List all services
+EOF
+    return 1
+  ;;
   esac
 }
 
diff --git a/setup/includes/stage b/setup/includes/stage
--- a/setup/includes/stage
+++ b/setup/includes/stage
@@ -49,27 +49,30 @@ stage_zero(){
     echo "/mnt is not mounted."
     exit 1
   fi
-  local scripts_path="${LIVE_PATH}/scripts/"
+  local tar_path="$SCRIPT_DIR/../system.tar"
 
   # Install the tarbar
-  if ! tar xvf "${LIVE_PATH}/system.tar" -C /mnt; then
+  if ! tar xvf "$tar_path" -C /mnt; then
     echo "Failed to extract system.tar." >&2
     exit 1
   fi
 
   echo "Generating file system table..."
-  "$scripts_path/genfstab" -U /mnt >>/mnt/etc/fstab
+  "$SCRIPT_DIR"/scripts/genfstab -U /mnt >>/mnt/etc/fstab
+  copy_scripts /mnt/bin/ /mnt/usr/lib/
 
+  echo "Copying services..."
+  if ! cp -rfv "$SCRIPT_DIR"/sv/* /mnt/etc/sv/; then
+    echo "Failed to copy services to /etc/sv/" >&2
+    exit 1
+  fi
 
-  echo "Moving scripts..."
-  cp -rv "$SCRIPT_DIR"/includes/* /mnt/opt/install/includes
-  cp -rv "$SCRIPT_DIR"/install /mnt/opt/install
-  cp -rv "$SCRIPT_DIR"/scripts/* /bin
-  cp -rv "$SCRIPT_DIR"/includes/utils /usr/lib/psi
-  cp -rv "$SCRIPT_DIR"/includes/service /usr/lib/psi
-  sudo chmod -R 755 /mnt/opt/install
-  sudo chmod -R 755 /bin
-  sudo chmod -R 755 /usr/lib/psi/utils
+  echo "Copying fonts..."
+  mkdir -p /mnt/usr/share/fonts/
+  if ! cp -rfv "$SCRIPT_DIR"/../fonts/* /mnt/usr/share/fonts/; then
+    echo "Failed to copy fonts to /mnt/usr/share/fonts/" >&2
+    exit 1
+  fi
 
   local hostname
   local username
@@ -109,7 +112,7 @@ stage_zero(){
   # mkdir -p /etc/alsa/conf.d
   # ln -s /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d
   # ln -s /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d
-  # insstall mesa-dri vulkan-loader (needed by wayfire)
+  # install mesa-dri vulkan-loader (needed by wayfire)
   # install wayfire
   # Instal alacritty
   # Install nerd-fonts
@@ -120,14 +123,8 @@ stage_zero(){
     xbps-install -uy
     xbps-install -y base-system
     xbps-remove -y base-container-full
-    if [[ -n \"\${stage0_packages_str}\" ]]; then
-      readarray -t stage0_packages <<< \"\${stage0_packages_str}\"
-      echo 'Installing basic packages' >&2
-          if ! install_xbps_packages \"\${stage0_packages[@]}\"; then
-              echo 'Failed to install xbps packages' >&2
-              exit 1
-          fi
-    fi
+    xbps-install -y fontconfig
+    fc-cache -fv
 
     echo \"\$hostname\" > /etc/hostname
     echo \"root:\$password\" | chpasswd -c SHA512
@@ -137,6 +134,7 @@ stage_zero(){
     echo \"\$username:\$password\" | chpasswd -c SHA512
     usermod -aG wheel \"\$username\"
     usermod -aG audio \"\$username\"
+    usermod -aG video \"\$username\"
     sed -i '/^#\s*%wheel ALL=(ALL:ALL) NOPASSWD: ALL/s/^# //' /etc/sudoers
 
     echo 'Preparing grub...'
@@ -149,6 +147,50 @@ stage_zero(){
         echo 'xbps-reconfigure failed' >&2
         exit 1
     fi
+
+    echo 'Installing packages...'>&2
+    if [[ -n \"\${stage0_packages_str}\" ]]; then
+      readarray -t stage0_packages <<< \"\${stage0_packages_str}\"
+      count=0
+      echo 'Installing basic packages' >&2
+      while ((count < 5)); do
+        if ! install_xbps_packages \"\${stage0_packages[@]}\"; then
+            echo 'Failed to install xbps packages...retrying' >&2
+            ((count++))
+            continue
+        fi
+        echo 'Successfully installed packages' >&2
+        break
+      done
+    fi
+
+    if ((count == 5)); then
+      echo 'Failed to install packages. Check internet connection and try again.' >&2
+      exit 1
+    fi
+
+    echo 'Performing services setup...'>&2
+    sleep 1
+    service -c /etc/runit/runsvdir/default/ dbus || true
+    service -c /etc/runit/runsvdir/default/ dhcpcd || true
+    service -c /etc/runit/runsvdir/default/ chronyd || true
+    service -c /etc/runit/runsvdir/default/ tlp || true
+    service -c /etc/runit/runsvdir/default/ rtkit || true
+    service -c /etc/runit/runsvdir/default/ seatd || true
+    service -c /etc/runit/runsvdir/default/ wpa_supplicant || true
+    service -c /etc/runit/runsvdir/default/ xdg-run-generator || true
+
+    if ! mkdir -p /etc/pipewire/pipewire.conf.d; then
+      echo \"Failed to create pipewire folder\"
+    fi
+
+    if ! ln -s /usr/share/examples/pipewire/20-pipewire-pulse.conf /etc/pipewire/pipewire.conf.d/; then
+      echo \"Pipewire configuration failed to link\"
+    fi
+
+    mkdir -p /etc/alsa/conf.d
+    ln -s /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d
+    ln -s /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d
 
     echo 'Preparing for stage 1...'
     mkdir -p /var/install/
diff --git a/setup/includes/utils b/setup/includes/utils
--- a/setup/includes/utils
+++ b/setup/includes/utils
@@ -16,30 +16,30 @@ function select_from_list() {
   local current_page=0
   local selected_item_index
   while true; do
-    clear
+    clear >&2
     local selection=0
     local start="$((current_page*max_items))"
     local index=$start
     local end=$((start + max_items < ${#list[@]} ? start + max_items : ${#list[@]}))
 
     while ((index < end)); do
-      echo "$selection ) ${list[$index]}"
+      echo "$selection ) ${list[$index]}" >&2
       selection=$((selection+1))
       index=$((index+1))
     done
 
     if (( current_page < page_count - 1)); then
-      echo "7 ) Next page"
+      echo "7 ) Next page" >&2
     fi
 
-    echo " "
+    echo " " >&2
 
     if (( current_page > 0 )); then
-      echo "8 ) Previous page"
+      echo "8 ) Previous page" >&2
     fi
-    echo "9 ) Exit"
-    echo "Page $((current_page)) / $page_count"
-    read -r -p "Select an option: " selection
+    echo "9 ) Exit" >&2
+    echo "Page $((current_page)) / $((page_count - 1))"
+    read -r -p "Select an option: " selection >&2
     case $selection in
       [0-6])
         local selected_item_index=$((selection + start))
@@ -86,7 +86,7 @@ export -f ask_for_confirmation
 # Function for checking if the user is root
 function check_root_user() {
   if [ "$(id -u)" != "0" ]; then
-    echo "Error: This script must be run as root"
+    echo "Error: This script must be run as root" >&2
     exit 1
   fi
 }
@@ -99,7 +99,7 @@ function get_current_stage_from_var() {
     if [[ -n $stage ]]; then
         echo "$stage"
     else
-        >&2 echo "No stage found."
+        echo "No stage found." >&2
         return 1  # Return an error code if no stage is found.
     fi
 }
