fix: bugs related to audio

diff --git a/setup/includes/stage b/setup/includes/stage
--- a/setup/includes/stage
+++ b/setup/includes/stage
@@ -135,6 +135,8 @@ stage_zero(){
   # Display manager not saving config
 
   copy_wpa_supplicant_conf
+  xbps-install -Suy xbps
+  xbps-install -y unzip
 
   x_chroot /mnt /bin/bash -c "
     if ! xbps-install -Suy xbps; then
@@ -199,11 +201,11 @@ stage_zero(){
       echo \"Failed to create pipewire folder\" >&2
     fi
 
-    if ! ln -s /usr/share/examples/wireplumber/10-wireplumber.conf /etc/pipewire/pipewire.conf.d/; then
+    if ! ln -sv /usr/share/examples/wireplumber/10-wireplumber.conf /etc/pipewire/pipewire.conf.d/; then
       echo \"WirePlumber configuration failed to link\" >&2
     fi
 
-    if ! ln -s /usr/share/examples/pipewire/20-pipewire-pulse.conf /etc/pipewire/pipewire.conf.d/; then
+    if ! ln -sv /usr/share/examples/pipewire/20-pipewire-pulse.conf /etc/pipewire/pipewire.conf.d/; then
       echo \"Pipewire configuration failed to link\"
     fi
 
@@ -211,12 +213,12 @@ stage_zero(){
       echo \"Failed to create alsa config directory\" >&2
     fi
 
-    if ! ln -s /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d/; then
+    if ! ln -sv /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d/; then
       echo \"Failed to link ALSA pipewire config\" >&2
     fi
 
-    if ! ln -s /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d/; then
-      ln -s /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d
+    if ! ln -sv /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d/; then
+      ln -sv /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d
     fi
 
     echo \"root:\$password\" | chpasswd -c SHA512
@@ -227,7 +229,7 @@ stage_zero(){
     usermod -aG audio \"\$username\"
     usermod -aG video \"\$username\"
     usermod -aG _seatd \"\$username\"
-    sed -i '/^#\s*%wheel ALL=(ALLd:ALL) ALL/s/^# //' /etc/sudoers
+    sed -i '/^#\s*%wheel ALL=(ALL:ALL) ALL/s/^# //' /etc/sudoers
 
     echo 'Performing services setup...'>&2
     for svc in dbus dhcpcd chronyd tlp rtkit seatd xdg-run-generator; do
@@ -239,15 +241,33 @@ stage_zero(){
 
   copy_configs "/mnt/home/$username" "$username"
 
-  map_string  "export XDG_RUNTIME_DIR=" "export XDG_RUNTIME_DIR=/run/user/\$(id -u)" /mnt/etc/profile.d/bash.sh
-  map_string "Exec=nnn" "Exec=alacritty -e nnn" /mnt/usr/share/applications/nnn.desktop
-  map_string "Exec=nvim %F" "Exec=alacritty -e nvim %F" /mnt/usr/share/applications/nvim.desktop
-  map_string "Exec=btop" "Exec=alacritty -e btop" /mnt/usr/share/applications/btop.desktop
+  if ! map_string  "export XDG_RUNTIME_DIR=" "export XDG_RUNTIME_DIR=/run/user/\$(id -u)" /mnt/etc/profile.d/bash.sh; then
+    echo "Failed to map XDG_RUNTIME_DIR" >&2
+  fi
 
-  mkdir -p /etc/udev/rules.d/
-  echo 'ACTION=="add", SUBSYSTEM=="backlight", GROUP="video", MODE="0664"' > /etc/udev/rules.d/90-backlight.rules
-  export_theme "Dracula" "/mnt/home/$username"
-  set_theme "Dracula"
+  if ! map_string "Exec=nnn" "Exec=alacritty -e nnn" /mnt/usr/share/applications/nnn.desktop; then
+    echo "Failed to map nnn" >&2
+  fi
+
+  if ! map_string "Exec=nvim %F" "Exec=alacritty -e nvim %F" /mnt/usr/share/applications/nvim.desktop; then
+    echo "Failed to map nvim" >&2
+  fi
+
+  if ! map_string "Exec=btop" "Exec=alacritty -e btop" /mnt/usr/share/applications/btop.desktop; then
+    echo "Failed to map btop" >&2
+  fi
+
+  if ! mkdir -p /mnt/etc/udev/rules.d/ ; then
+    echo "Failed to create udev rules directory" >&2
+  fi
+  if ! echo 'ACTION=="add", SUBSYSTEM=="backlight", GROUP="video", MODE="0664"' > /mnt/etc/udev/rules.d/
+  backlight.rules; then
+    echo "Failed to create udev rule" >&2
+  fi
+
+  if ! export_theme "Dracula" "/mnt/home/$username"; then
+    echo "Failed to export theme" >&2
+  fi
 
   echo 'Install complete. Rebooting into the system'
   sleep 5
diff --git a/setup/includes/utils b/setup/includes/utils
--- a/setup/includes/utils
+++ b/setup/includes/utils
@@ -217,7 +217,8 @@ export -f x_chroot
 function export_theme(){
     local theme=$1
     local user_home=$2
-    local theme_file="$SCRIPT_DIR"/../theme/dracula.zip
+    local theme_file
+    theme_file=$(find "$SCRIPT_DIR/../theme/" -type f -iname "$theme.*")
     local tmp_dir
     if [[ ! -f "$theme_file" ]]; then
         echo "Theme file not found: $theme_file" >&2
@@ -225,17 +226,22 @@ function export_theme(){
     fi
     tmp_dir=$(mktemp -d)
     local theme_dir="$user_home/.local/share/themes/$theme"
-    mkdir -p "$theme_dir"
-    tar xf "$theme_file" -C "$tmp_dir"
+    if ! mkdir -pv "$theme_dir"; then
+        echo "Failed to create theme directory: $theme_dir" >&2
+        return 1
+    fi
 
-    # Copy contents to theme directory
-    # Using /* to expand contents and not the directory itself
-    cp -r "$tmp_dir"/*/* "$theme_dir"/
+    if ! unzip "$theme_file" -d "$tmp_dir"; then
+        echo "Failed to extract theme" >&2
+        return 1
+    fi
 
-    # Cleanup
-    rm -rf "$tmp_dir"
+    if ! mv "$tmp_dir"/*/* "$theme_dir"/; then
+        echo "Failed to move theme files" >&2
+        return 1
+    fi
 
     # Set permissions
-    chown -R $(stat -c '%u:%g' "$user_home") "$theme_dir"
+    chown -Rv $(stat -c '%u:%g' "$user_home") "$theme_dir"  # -v added
 }
-
+export -f export_theme
